AllCops:

  NewCops: enable

  DisplayCopNames: true

  DisplayStyleGuide: true

  Include:
    - '**/Rakefile'


Security/Eval:
  Enabled: false


Layout/LineLength:
  Max: 100


Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: false
