AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - "**/Rakefile"

Layout/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
