AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'

Layout/LineLength:
  Max: 100

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: false
